"""Run contract-bound, label-free Gate 7 dual-lane batch inference.

This engineering entry point is not a model-selection, calibration, or
performance-evaluation interface.  It reads only a CSV containing ``smiles``
and optional ``input_id``, then uses the already smoke-verified R2 inference
path.  Numerical rows remain technical predictions not authorized as a unified
numeric release; F remains status-only.
"""
from __future__ import annotations

import argparse
import json
from pathlib import Path

import numpy as np
import pandas as pd

from pipeline_common import ROOT, finish_stage, run_cli, sha256, stage_output, verify_stage
from smoke_gate7_release_interface import (
    CONTRACT_STAGE,
    frame_hash,
    read_json,
    read_label_free_input,
    render_rows,
)


CARD_STAGE = "gate7_model_data_card_availability_audit"
STAGE = "gate7_dual_lane_batch_inference"
SCHEMA_VERSION = "gate7_dual_lane_output_v1"
REQUIRED_OUTPUT_COLUMNS = [
    "input_row", "input_id", "smiles", "task_id", "endpoint", "model_lane", "model_version",
    "prediction_status", "predicted_physical", "unit", "nearest_train_tanimoto", "ad_threshold",
    "applicability_domain", "ad_method", "ad_release_status", "uncertainty_technical_source",
    "uncertainty_release_status", "evidence_status", "test_lifecycle", "limitation",
    "publication_action",
]


def card_metadata(root: Path) -> tuple[pd.DataFrame, Path]:
    folder = root / "results/analysis/gate7_model_data_card_audit_v1"
    metadata = verify_stage(folder, CARD_STAGE)
    if metadata.get("unified_numeric_release_authorized"):
        raise ValueError("R3 unexpectedly authorizes a unified numeric release")
    audit = pd.read_csv(folder / "endpoint_ad_uncertainty_audit.csv", keep_default_na=False)
    required = {
        "task_id", "ad_method", "ad_threshold", "ad_release_status", "uncertainty_technical_source",
        "uncertainty_release_status", "publication_action",
    }
    if len(audit) != 7 or audit.task_id.duplicated().any() or not required <= set(audit.columns):
        raise ValueError("Gate 7 R3 AD/uncertainty card is incomplete")
    audit = audit.loc[:, sorted(required)].rename(columns={"ad_threshold": "card_ad_threshold"})
    return audit, folder


def render_release_rows(root: Path, contract: dict, input_frame: pd.DataFrame, cards: pd.DataFrame) -> pd.DataFrame:
    """Decorate the R2-verified predictions with R3 availability metadata."""
    output = render_rows(root, contract, input_frame)
    output = output.merge(cards, on="task_id", how="left", validate="many_to_one")
    if output.ad_method.isna().any() or len(output) != len(input_frame) * len(contract["tasks"]):
        raise ValueError("A R3 card is absent for a contract task")
    numeric = output.endpoint.ne("F")
    card_threshold = pd.to_numeric(output.card_ad_threshold, errors="coerce")
    if not np.allclose(
        output.loc[numeric, "ad_threshold"].to_numpy(float),
        card_threshold.loc[numeric].to_numpy(float),
        equal_nan=False,
    ):
        raise ValueError("R2 technical AD thresholds disagree with the verified R3 card")
    output = output.drop(columns="card_ad_threshold")
    output.loc[numeric, "prediction_status"] = "technical_prediction_available_not_release_authorized"
    output.loc[numeric, "publication_action"] = (
        "technical output only; not a performance claim, calibrated interval, or unified numeric release"
    )
    output = output.loc[:, REQUIRED_OUTPUT_COLUMNS].copy()
    if list(output.columns) != REQUIRED_OUTPUT_COLUMNS:
        raise ValueError("Gate 7 R4 output schema ordering drifted")
    f_rows = output.endpoint.eq("F")
    if not (
        output.loc[f_rows, "prediction_status"].eq("not_available_exploratory").all()
        and output.loc[f_rows, "predicted_physical"].isna().all()
        and output.loc[f_rows, "applicability_domain"].eq("not_applicable").all()
    ):
        raise ValueError("F status-only release rule was violated")
    if output.loc[numeric, "predicted_physical"].isna().any() or not np.isfinite(
        output.loc[numeric, "predicted_physical"].to_numpy(float)
    ).all():
        raise ValueError("A numeric Gate 7 task failed to produce finite technical output")
    if not output.loc[numeric, "prediction_status"].eq("technical_prediction_available_not_release_authorized").all():
        raise ValueError("Numeric prediction status is inconsistent with the frozen release boundary")
    return output


def write_readme(folder: Path, smoke: bool) -> None:
    mode = "technical smoke" if smoke else "label-free batch inference"
    folder.joinpath("README.md").write_text(
        "# Gate 7 R4 dual-lane batch inference\n\n"
        f"This immutable output was generated by {mode} using only `smiles` and optional `input_id`. "
        "It reads no labels and computes no performance metric. The contract-bound model assets are not retrained, "
        "calibrated, selected, or replaced.\n\n"
        "Six numeric tasks return technical predictions together with model lane/version, similarity/AD metadata, "
        "uncertainty availability, evidence lifecycle, and limitations. These are not a unified authorized numeric "
        "release, calibrated predictive intervals, or new efficacy claims. F always returns status-only with no number.\n",
        encoding="utf-8",
    )


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--root", type=Path, default=ROOT)
    parser.add_argument("--contract", type=Path)
    parser.add_argument("--input", type=Path, required=True, help="CSV with only smiles and optional input_id")
    parser.add_argument("--output", type=Path, required=True, help="New immutable output directory")
    parser.add_argument("--confirm-no-label-inference", action="store_true")
    parser.add_argument("--technical-smoke", action="store_true", help="Require 2--8 rows and verify in-process repeat determinism")
    parser.add_argument("--check-only", action="store_true")
    args = parser.parse_args()
    root = args.root.resolve()
    contract_dir = args.contract or root / "data/public_development/gate7_release_contract_v2"
    verify_stage(contract_dir, CONTRACT_STAGE)
    contract = read_json(contract_dir / "release_contract.json")
    if contract.get("numeric_release_authorized") is not False:
        raise ValueError("Gate 7 R1 contract does not preserve the technical-only release boundary")
    cards, card_dir = card_metadata(root)
    input_frame = read_label_free_input(args.input, rows_min=2 if args.technical_smoke else 1,
                                        rows_max=8 if args.technical_smoke else None)
    if args.check_only:
        print(f"Gate 7 R4 CLI preflight: rows={len(input_frame)} tasks={len(contract['tasks'])}; labels not read.")
        return
    if not args.confirm_no_label_inference:
        raise ValueError("Gate 7 R4 requires --confirm-no-label-inference")
    with stage_output(args.output) as folder:
        first = render_release_rows(root, contract, input_frame, cards)
        max_difference = None
        if args.technical_smoke:
            second = render_release_rows(root, contract, input_frame, cards)
            numeric = first.predicted_physical.notna()
            difference = np.abs(first.loc[numeric, "predicted_physical"].to_numpy(float)
                                - second.loc[numeric, "predicted_physical"].to_numpy(float))
            max_difference = float(difference.max(initial=0.0))
            if max_difference > 1e-12:
                raise ValueError(f"Gate 7 R4 technical-smoke repeat determinism failed: {max_difference:.3g}")
        input_frame.to_csv(folder / "submitted_label_free_input.csv", index=False)
        first.to_csv(folder / "dual_lane_predictions.csv", index=False)
        assertions = {
            "output_schema_version": SCHEMA_VERSION,
            "technical_smoke": bool(args.technical_smoke),
            "input_rows": int(len(input_frame)),
            "output_rows": int(len(first)),
            "expected_output_rows": int(len(input_frame) * len(contract["tasks"])),
            "numeric_prediction_rows": int(first.predicted_physical.notna().sum()),
            "f_status_only_rows": int(first.endpoint.eq("F").sum()),
            "all_numeric_predictions_finite": True,
            "f_status_only_rule_passed": True,
            "no_labels_accessed": True,
            "performance_metrics_computed": False,
            "unified_numeric_release_authorized": False,
            "max_abs_repeat_prediction_difference": max_difference,
            "repeat_tolerance": 1e-12 if args.technical_smoke else None,
        }
        (folder / "inference_assertions.json").write_text(json.dumps(assertions, ensure_ascii=False, indent=2), encoding="utf-8")
        manifest = {
            "output_schema_version": SCHEMA_VERSION,
            "contract_dir": str(contract_dir.resolve()),
            "contract_complete_sha256": sha256(contract_dir / "complete.json"),
            "card_dir": str(card_dir.resolve()),
            "card_complete_sha256": sha256(card_dir / "complete.json"),
            "input_path": str(args.input.resolve()),
            "input_sha256": sha256(args.input),
            "normalized_input_sha256": frame_hash(input_frame),
            "no_labels_accessed": True,
            "no_performance_metrics_computed": True,
            "no_model_fitted": True,
            "no_calibration": True,
            "no_candidate_selection_changed": True,
            "unified_numeric_release_authorized": False,
        }
        (folder / "run_manifest.json").write_text(json.dumps(manifest, ensure_ascii=False, indent=2), encoding="utf-8")
        write_readme(folder, args.technical_smoke)
        finish_stage(
            folder, STAGE,
            inputs={
                str((contract_dir / "complete.json").resolve()): sha256(contract_dir / "complete.json"),
                str((card_dir / "complete.json").resolve()): sha256(card_dir / "complete.json"),
                str(args.input.resolve()): sha256(args.input),
            },
            partial=False, no_model_fitted=True, no_labels_accessed=True,
            no_performance_metrics_computed=True, no_calibration=True,
            no_candidate_selection_changed=True, technical_predictions_generated=True,
            unified_numeric_release_authorized=False, technical_smoke=bool(args.technical_smoke),
            input_rows=int(len(input_frame)), output_rows=int(len(first)),
            max_abs_repeat_prediction_difference=max_difference,
        )
    print(f"Gate 7 R4 dual-lane inference: {args.output}")


if __name__ == "__main__":
    run_cli(main)
